name: yamus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# flutter pub run build_runner watch --delete-conflicting-outputs / build 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service:
    path: ./packages/audio_service/audio_service
  audio_session: ^0.1.0
  collection: ^1.15.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  flutter_secure_storage: ^4.1.0
  http: ^0.13.3
  json_annotation: ^4.0.0
  just_audio: ^0.7.4+1
  persistent_bottom_nav_bar: ^4.0.2
  provider: ^5.0.0
  retrofit: ^2.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  uni_links: ^0.5.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
