blank_issues_enabled: false
contact_links:
  - name: Stack Overflow
    url: https://stackoverflow.com/search?q=audio_service
    about: Ask here if it's not a bug report, documentation request or feature request.
  - name: Gitter
    url: https://gitter.im/flutter/flutter
    about: Ask here if you want to have a live chat with other Flutter developers.
